services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     oc_platform.antispam:
        class: OC\PlatformBundle\OcAntispam
        arguments:
          - "@mailer"
          - %locale%
          - 50