<?php

namespace OC\PlatformBundle\Repository;

/**
 * SkilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkilRepository extends \Doctrine\ORM\EntityRepository
{
}
